name: Github Actions For  W-95 Blog
on:
  push:
    branches:
      master
jobs:
  build-blog:
    name: my_build_job_for_blog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: /dist
          BUILD_SCRIPT: npm install && npm run build 
